version: '3'

services:
  db:
    build:
      context: ./docker
      dockerfile: postgres.docker
    volumes:
      - ./db_data:/var/lib/postgresql/
    environment:
      POSTGRES_PASSWORD: 1234567
      POSTGRES_USER: db
      POSTGRES_DB: currency
    ports:
      - "54320:5432"
    env_file:
      - .env